version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: P@ssw0rd
    # volumes:
    #   - .data/postgres:/var/lib/postgresql
    ports:
      - "10023:5432"
    restart: always